
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAmountOfPLN", targetNamespace = "http://service/", className = "service.GetAmountOfPLN")
    @ResponseWrapper(localName = "getAmountOfPLNResponse", targetNamespace = "http://service/", className = "service.GetAmountOfPLNResponse")
    @Action(input = "http://service/CalculatorService/getAmountOfPLNRequest", output = "http://service/CalculatorService/getAmountOfPLNResponse")
    public double getAmountOfPLN(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExchangeRate", targetNamespace = "http://service/", className = "service.GetExchangeRate")
    @ResponseWrapper(localName = "getExchangeRateResponse", targetNamespace = "http://service/", className = "service.GetExchangeRateResponse")
    @Action(input = "http://service/CalculatorService/getExchangeRateRequest", output = "http://service/CalculatorService/getExchangeRateResponse")
    public double getExchangeRate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
