
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HolidayServiceService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/holiday_service_war_exploded/HolidayService?wsdl")
public class HolidayServiceService
    extends Service
{

    private final static URL HOLIDAYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HOLIDAYSERVICESERVICE_EXCEPTION;
    private final static QName HOLIDAYSERVICESERVICE_QNAME = new QName("http://service/", "HolidayServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/holiday_service_war_exploded/HolidayService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOLIDAYSERVICESERVICE_WSDL_LOCATION = url;
        HOLIDAYSERVICESERVICE_EXCEPTION = e;
    }

    public HolidayServiceService() {
        super(__getWsdlLocation(), HOLIDAYSERVICESERVICE_QNAME);
    }

    public HolidayServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOLIDAYSERVICESERVICE_QNAME, features);
    }

    public HolidayServiceService(URL wsdlLocation) {
        super(wsdlLocation, HOLIDAYSERVICESERVICE_QNAME);
    }

    public HolidayServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOLIDAYSERVICESERVICE_QNAME, features);
    }

    public HolidayServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolidayServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HolidayService
     */
    @WebEndpoint(name = "HolidayServicePort")
    public HolidayService getHolidayServicePort() {
        return super.getPort(new QName("http://service/", "HolidayServicePort"), HolidayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolidayService
     */
    @WebEndpoint(name = "HolidayServicePort")
    public HolidayService getHolidayServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "HolidayServicePort"), HolidayService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOLIDAYSERVICESERVICE_EXCEPTION!= null) {
            throw HOLIDAYSERVICESERVICE_EXCEPTION;
        }
        return HOLIDAYSERVICESERVICE_WSDL_LOCATION;
    }

}
