
package service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolidayService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolidayService {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNumberOfDays", targetNamespace = "http://service/", className = "service.GetNumberOfDays")
    @ResponseWrapper(localName = "getNumberOfDaysResponse", targetNamespace = "http://service/", className = "service.GetNumberOfDaysResponse")
    public long getNumberOfDays();

}
