
package pl.agh.soa.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SensorService", targetNamespace = "http://soap.soa.agh.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SensorService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "occupyPlace", targetNamespace = "http://soap.soa.agh.pl/", className = "pl.agh.soa.soap.client.OccupyPlace")
    @ResponseWrapper(localName = "occupyPlaceResponse", targetNamespace = "http://soap.soa.agh.pl/", className = "pl.agh.soa.soap.client.OccupyPlaceResponse")
    public void occupyPlace(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "releasePlace", targetNamespace = "http://soap.soa.agh.pl/", className = "pl.agh.soa.soap.client.ReleasePlace")
    @ResponseWrapper(localName = "releasePlaceResponse", targetNamespace = "http://soap.soa.agh.pl/", className = "pl.agh.soa.soap.client.ReleasePlaceResponse")
    public void releasePlace(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2);

}
