
package pl.agh.soa.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SensorServiceService", targetNamespace = "http://soap.soa.agh.pl/", wsdlLocation = "http://localhost:8080/parking_connector/SensorService?wsdl")
public class SensorServiceService
    extends Service
{

    private final static URL SENSORSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SENSORSERVICESERVICE_EXCEPTION;
    private final static QName SENSORSERVICESERVICE_QNAME = new QName("http://soap.soa.agh.pl/", "SensorServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/parking_connector/SensorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENSORSERVICESERVICE_WSDL_LOCATION = url;
        SENSORSERVICESERVICE_EXCEPTION = e;
    }

    public SensorServiceService() {
        super(__getWsdlLocation(), SENSORSERVICESERVICE_QNAME);
    }

    public SensorServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENSORSERVICESERVICE_QNAME, features);
    }

    public SensorServiceService(URL wsdlLocation) {
        super(wsdlLocation, SENSORSERVICESERVICE_QNAME);
    }

    public SensorServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENSORSERVICESERVICE_QNAME, features);
    }

    public SensorServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SensorServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SensorService
     */
    @WebEndpoint(name = "SensorServicePort")
    public SensorService getSensorServicePort() {
        return super.getPort(new QName("http://soap.soa.agh.pl/", "SensorServicePort"), SensorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SensorService
     */
    @WebEndpoint(name = "SensorServicePort")
    public SensorService getSensorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.soa.agh.pl/", "SensorServicePort"), SensorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENSORSERVICESERVICE_EXCEPTION!= null) {
            throw SENSORSERVICESERVICE_EXCEPTION;
        }
        return SENSORSERVICESERVICE_WSDL_LOCATION;
    }

}
